version: '3.7'
services:
  nodejs:
    build: ./.docker/nodejs
    expose:
      - "3000"
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: "3000"
    ports:
       - "3000:3000"
    volumes: 
      - "./:/usr/src/app/"
    networks:
      - "ensiie"
    
  postgres:
    build:
      context: ./.docker/postgres
    ports:
      - "${DB_PORT_EXTERNAL}:${DB_PORT_EXTERNAL}"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB="ensiie"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - .:/var/www/html
    working_dir: /var/www/html
volumes:
    postgres-data-volume:
         external: true

    networks:
      - "ensiie"
  mountebank:
    container_name: mountebank
    image: jkris/mountebank:latest
    volumes:
    - ./imposters:/imposters
    ports:
    - 2525:2525
    - 8090:8090
    command: --configfile /imposters/imposters.ejs --allowInjection
networks:
  ensiie:
    driver: bridge
