version: '3.7'
services:
  nodejs:
    build: ./.docker/nodejs
    expose:
      - "3000"
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: "3000"
    ports:
       - "3000:3000"
    volumes: 
      - "./:/usr/src/app/"
    
  postgres:
    build:
      context: ./.docker/postgres
    ports:
      - ${DB_PORT_EXTERNAL}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data:z
      - .:/var/www/html
    working_dir: /var/www/html
volumes:
    postgres-data-volume:
         external: true
